/* This file was auto-generated by shenanigans-manager */
define(["require", "exports", "chai", "sinon-chai", "mocha"], function (
    require,
    exports,
    chai,
    sinonChai
) {
    "use strict";

    chai.use(sinonChai);
    mocha.setup({
        ui: "bdd",
    });

    /**
     * Informs RequireJS of the file location for test dependencies.
     *
     * @param dependencies   Modules depended upon for tests.
     */
    const redirectTestDependencies = (dependencies) => {
        requirejs.config({
            packages: dependencies.map((dependency) => {
                return {
                    main: "index",
                    name: dependency,
                };
            }),
        });

        for (const dependencyUpper of dependencies) {
            const dependency = dependencyUpper.toLowerCase();

            requirejs.config({
                paths: {
                    [dependency]: `../../../packages/${dependency}/lib`,
                },
            });
        }
    };

    /**
     * Recursively loads test paths.
     *
     * @param loadingPaths   Test paths to load.
     * @param i   Which index test path to load.
     * @param onComplete   A callback for when loading is done.
     */
    const loadTestPaths = (loadingPaths, i, onComplete) => {
        if (i >= loadingPaths.length) {
            onComplete();
            return;
        }

        requirejs([loadingPaths[i]], () => {
            loadTestPaths(loadingPaths, i + 1, onComplete);
        });
    };

    (() => {
        redirectTestDependencies(testDependencies);
        loadTestPaths(testPaths, 0, function () {
            mocha.run();
        });
    })();
});
