language: node_js

node_js:
  - "node"

script:
  npm run setup && npm run verify:coverage

# Recommended workaround for https://github.com/travis-ci/travis-ci/issues/8836
sudo: required
addons:
  chrome: stable
