version: 2.1

references:
  default_env: &default_env
    docker:
      - image: circleci/node:14.4.0

  repo_cache_key_1: &repo_cache_key_1 v1-repo-{{ checksum "yarn.lock" }}-{{ .Branch }}-{{ .Revision }}
  repo_cache_key_2: &repo_cache_key_2 v1-repo-{{ checksum "yarn.lock" }}-{{ .Branch }}
  repo_cache_key_3: &repo_cache_key_3 v1-repo-{{ checksum "yarn.lock" }}

  restore_repo_cache: &restore_repo_cache
    restore_cache:
      keys:
        - *repo_cache_key_1
        - *repo_cache_key_2
        - *repo_cache_key_3

  save_repo_cache: &save_repo_cache
    save_cache:
      key: *repo_cache_key_1
      paths:
        - .

jobs:
  checkout:
    <<: *default_env
    steps:
      - *restore_repo_cache
      - checkout
      - run: yarn --production=false --frozen-lockfile
      - *save_repo_cache

  format:
    <<: *default_env
    steps:
      - *restore_repo
      - run:
          name: Verify Prettier
          command: yarn format

  lint:
    <<: *default_env
    steps:
      - *restore_repo
      - run:
          name: Verify Prettier
          command: yarn lint

  test:
    <<: *default_env
    steps:
      - *restore_repo
      - run:
          name: Verify Prettier
          command: yarn test

workflows:
  run-everything:
    jobs:
      - checkout
      - compile:
          requires:
            - checkout
      - format:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - test:
          requires:
            - checkout
            - compile