import { SpriteMultiple } from "./SpriteMultiple";
import { SpriteSingle } from "./SpriteSingle";

/**
 * A single [red, green, blue, alpha] pixel's colors.
 */
export type IPixel = [number, number, number, number];

/**
 * A palette of potential pixel colors.
 */
export type IPalette = IPixel[];

/**
 * Raw sprite data for a library.
 */
export interface ILibraryRaws {
    [i: string]: ILibraryRaws | string | any[];
}

/**
 * A base container for storing raw sprites and their renders.
 */
export interface ILibrary {
    /**
     * The original sources for the sprites.
     */
    readonly raws: ILibraryRaws;

    /**
     * Rendered sprites from the raw sources.
     */
    readonly sprites: IRenderLibrary;
}

/**
 * Rendered sprite data generated from a source sprite.
 */
export interface IRender {
    /**
     * The original raw command that generated this render.
     */
    source: ICommand;

    /**
     * Output sprites generated by the source.
     */
    sprites: IRenderSprites;

    /**
     * An optional filter to change colors by, if source is a "filter" command.
     */
    filter?: IFilterAttributes;

    /**
     * Any containers storing this IRender.
     */
    containers: IRenderContainerListing[];
}

/**
 * Generated sprites stored within an IRender.
 */
export interface IRenderSprites {
    [i: string]: SpriteSingle | SpriteMultiple;
}

/**
 * References to contains that store an IRender.
 */
export interface IRenderContainerListing {
    /**
     * A container storing the listing's IRender.
     */
    container: IRenderLibrary;

    /**
     * The key under which the IRender is stored.
     */
    key: string;
}

/**
 * A searchable storage tree of IRenders.
 */
export interface IRenderLibrary {
    [i: string]: IRenderLibrary | IRender;
}

/**
 * Information for expanding a sprite, such as a PixelDrawr's IThing.
 */
export interface ISpriteAttributes {
    spriteheight?: number;
    spritewidth?: number;
    filter?: IFilter;
}

/**
 * A raw sprite, as either the pixel String or Array of commands.
 */
export type ICommand = string | any[];

/**
 * A "filter" command, as ["filter", [source path], "<filter name>"].
 */
export type IFilterCommand = [string, string[], string];

/**
 * A "multiple" command, as ["multiple", "<direction>", <sprites>].
 */
export type IMultipleCommand = [string, string, ISpriteMultipleSettings];

/**
 * A "same" command, as ["same", [source path]].
 */
export type ISameCommand = [string, string[]];

export interface IFilter {
    0: string;
    1: {
        [i: string]: string;
    };
}

export interface IFilterContainer {
    [i: string]: IFilter;
}

export interface IFilterAttributes {
    filter: IFilter;
}

/**
 * A transformation Function to apply to input.
 *
 * @param data   The raw input data to be transformed.
 * @param key   They key under which the data is to be stored.
 * @param attributes   Any extra attributes to be given to the transforms.
 * @returns The input data, transformed.
 */
export type ITransform = (data: any, key: string, attributes: any) => any;

/**
 * Raw settings to generate an ISpriteMultiple.
 */
export interface ISpriteMultipleSettings {
    /**
     * Raw sprite component for the top section.
     */
    top?: string;

    /**
     * How many pixels tall the top section is, if it exists.
     */
    topheight?: number;

    /**
     * Raw sprite component for the right section.
     */
    right?: string;

    /**
     * How many pixels wide the right section is, if it exists.
     */
    rightwidth?: number;

    /**
     * Raw sprite component for the bottom section.
     */
    bottom?: string;

    /**
     * How many pixels tall the bottom section is, if it exists.
     */
    bottomheight?: number;

    /**
     * Raw sprite component for the left section.
     */
    left?: string;

    /**
     * How many pixels wide the left section is, if it exists.
     */
    leftwidth?: number;

    /**
     * Raw sprite component for the center section.
     */
    middle?: string;

    /**
     * Whether the center section should stretch to fill its space.
     */
    middleStretch?: boolean;
}

/**
 * Storage for an ISpriteMultiple's generated sprites.
 */
export interface ISpriteSingles {
    [i: string]: SpriteSingle;
}

/**
 * Generates a sprite from a render.
 *
 * @param render   The source render.
 * @param key   Key for the sprite.
 * @param attributes   Any attributes to pass to a sprite generator.
 * @returns The generated sprite from the render.
 */
export type IGeneralSpriteGenerator = (
    render: IRender,
    key: string,
    attributes: any
) => SpriteSingle | SpriteMultiple;

/**
 * Settings to initialize a new IPixelRendr.
 */
export interface IPixelRendrSettings {
    /**
     * The default palette of colors to use for sprites.
     */
    paletteDefault?: IPalette;

    /**
     * A nested library of sprites to process.
     */
    library?: any;

    /**
     * Filters that may be used by sprites in the library.
     */
    filters?: IFilterContainer;

    /**
     * An amount to expand sprites by when processing (by default, 1 for not at
     * all).
     */
    scale?: number;

    /**
     * What sub-class in decode keys should indicate a sprite is to be flipped
     * vertically (by default, "flip-vert").
     */
    flipVert?: string;

    /**
     * What sub-class in decode keys should indicate a sprite is to be flipped
     * horizontally (by default, "flip-vert").
     */
    flipHoriz?: string;

    /**
     * What key in attributions should contain sprite widths (by default,
     * "spriteWidth").
     */
    spriteWidth?: string;

    /**
     *  What key in attributions should contain sprite heights (by default,
     * "spriteHeight").
     */
    spriteHeight?: string;
}
