/* This file was auto-generated by shenanigans-manager */

import { IMapRaw } from "../src/components/maps";
import { {{shenanigans.name}} } from "./{{shenanigans.name}}";
import { stub{{shenanigans.name}} } from "./fakes";

const describeLocation = (map: IMapRaw, locationName: string) => {
    it(locationName, (): void => {
        const game: {{shenanigans.name}} = stub{{shenanigans.name}}();

        game.maps.setMap(map.name, locationName);
    });
};

const describeMap = (map: IMapRaw): void => {
    describe(map.name, (): void => {
        for (const i in map.locations) {
            describeLocation(map, i);
        }
    });
};

describe("Maps", (): void => {
    const game: {{shenanigans.name}} = stub{{shenanigans.name}}();

    for (const i in game.moduleSettings.maps.library!) {
        describeMap(game.moduleSettings.maps.library![i]);
    }
});
