name: Compile

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: yarn compile
